public enum TokenType {
    TRUE, FALSE, NUMBER, STRING, NONE,

    PLUS, MINUS, MULT, DIV,
    NOT_EQUAL, EQUAL, GREATER, GREATER_EQUAL, LESS, LESS_EQUAL,
    AND, OR, NOT,

    LEFT_PAREN, RIGHT_PAREN,

    SEMICOLON, OPEN_BRACE, CLOSE_BRACE,
    VAR, IDENTIFIER, ASSIGN,
    WRITE,
    IF, ELSE, WHILE, FOR,

    FUNC, COMMA, RETURN,
    CLASS, SUPER, THIS, DOT,

    EOF
}

